version: '3'
services:
  telegram-bots:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MAIN_BOT_TOKEN=${MAIN_BOT_TOKEN}
      - INFO_BOT_TOKEN=${INFO_BOT_TOKEN}
    ports:
      - "8080:8080"  # Expose the port to Render
